### ISSUE TITLE
22w连接数，CPU内存低，负载非常高，最高达到50694

### ISSUE THREAD

**Issue by raintears2** [tennessine/ask#2]
22w连接数，CPU内存低，负载非常高，最高达到50694
这种是什么原因导致负载非常高，有解决办法吗？

------------------------------------------------LOAD------------------------------------------------
17:20:07 up 1 day, 20:24,  3 users,  load average: 8771.05, 2854.01, 1025.73

------------------------------------------------CPU------------------------------------------------
Cpu(s):  2.2%us,  3.6%sy,  0.0%ni, 92.1%id,  0.2%wa,  0.0%hi,  1.9%si,  0.0%st

------------------------------------------------MEM------------------------------------------------
             total       used       free     shared    buffers     cached
Mem:         32068       6677      25390          0        125        130
-/+ buffers/cache:       6421      25646
Swap:        11423          0      11423

------------------------------------------------TCP------------------------------------------------

 220533 ESTAB
   1940 TIME-WAIT
    776 LISTEN
    178 LAST-ACK
      8 SYN-SENT
      3 FIN-WAIT-1
      1 SYN-RECV
      1 State
      1 CLOSING

------------------------------------------------socket stats------------------------------------------------
sockets: used 221634
TCP: inuse 221508 orphan 184 tw 1871 alloc 221509 mem 91536
UDP: inuse 261 mem 259
UDPLITE: inuse 0
RAW: inuse 0
FRAG: inuse 0 memory 0
http1.server.com

**Comment by tennessine** [comment]
CPU的平均负载取决于cpu内核数量，如果我有8个进程程需要处理，4核CPU一次可以处理4个，等待中的也有4个
这时候负载就是4，而每个进程CPU只需要占用一个内核1%的CPU利用率，CPU总利用率是1%，如果这种进程数持续增多，就会出现高负载低利用率的情况
你遇到的就是这种问题，这样效率很低。
所以控制你的最大进程并发数或者增加CPU的内核（虚拟机）可以解决这种问题

我百度上找的 我也不是很懂
